---
version: '3.7'

services:
  check:
    container_name: check
    image: centos:centos7
    tty: true

  proxy:
    container_name: proxy
    build: ./proxy
    deploy:
      replicas: 1
    volumes:
      - ./proxy/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  web_flask:
    container_name: web_flask
    build: ./webapp_flask
    deploy:
      replicas: 1

  web_go:
    container_name: web_go
    build: ./webapp_go
    deploy:
      replicas: 1
