---
version: '3.7'

services:
  check:
    container_name: check
    hostname: check_server
    image: centos:centos7
    tty: true

  proxy:
    container_name: proxy
    hostname: reverse_proxy
    build: ./proxy
    deploy:
      replicas: 1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  web_flask:
    container_name: web_flask
    hostname: web_flask
    build: ./webapp_flask
    deploy:
      replicas: 1

  web_flask_2:
    container_name: web_flask_2
    hostname: web_flask_2
    build: ./webapp_flask_2
    deploy:
      replicas: 1

  web_go:
    container_name: web_go
    hostname: web_flask
    build: ./webapp_go
    deploy:
      replicas: 1

networks:
  default:
    ipam:
      config:
        - subnet: 192.168.2.0/24
